#!/bin/bash

# This is script to first run when restoring
# Will rsync home, dots, Srv folder to $HOME directory
set -euo pipefail

### VAR
USB="/run/media/$USER/netac"
# Only things you really want to loop over:
DIRS=(Documents Pictures Obsidian Working Shared VM Codes Videos .ssh)

# Optional sanity check
if [ ! -d "$USB/home" ]; then
  echo "ERROR: $USB/home does not exist"
  exit 1
fi

mkdir -p "$HOME/.config/Thunar"
mkdir -p "$HOME/.config/com.ml4w.hyprlandsettings"
mkdir -p "$HOME/.local/share/icons"

### Disable warning line
### SDDM Autologin user: ralexander
sed -i 's|^autogenerated = 1|# autogenerated = 1|' "$HOME/.config/hypr/hyprland.conf"
sleep 2
sudo sed -i '/^User=/s//User=ralexander/' /usr/lib/sddm/sddm.conf.d/default.conf
sleep 2

# Thunar custom actions XML
rsync -Prah "$USB/dots/uca.xml" "$HOME/.config/Thunar/"

# Main home directories
for d in "${DIRS[@]}"; do
  rsync -Prah "$USB/home/$d" "$HOME/"
done

# Icons & themes
rsync -Prah "$USB/home/LyraX-cursors" "$HOME/.local/share/icons/"
rsync -Prah "$USB/home"/{.icons,.themes} "$HOME/"

# Dotfiles tree (contents into $HOME)
rsync -Prah "$USB/dots/" "$HOME/"

# Srv backup into $HOME/Srv (if you really want it there)
rsync -Prah "$USB/Srv/" "$HOME/Srv/"

# Samba config into place (needs root)
sudo rsync -Prah "$USB/Srv/samba/"/{smb.conf,euclid} /etc/samba/

sleep 2
clear

### Font install NerdFont 3.4.0
bash "$HOME/Shared/fonts/install.sh" ; sleep 2 ; clear

### Install yay
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && sleep 2

### flatpak dot-installer for ml4w
flatpak install flathub com.ml4w.dotfilesinstaller && sleep 2

### run dotfileinstaller by hand
# https://raw.githubusercontent.com/mylinuxforwork/dotfiles/main/hyprland-dotfiles-stable.dotinst
