#!/usr/bin/env bash

set -u

QUIET=true
TOTAL_STEPS=8
STEP=0

status() {
  printf '%s\n' "$*"
}

progress() {
  STEP=$((STEP + 1))
  status "[$STEP/$TOTAL_STEPS] $1"
}

err() {
  printf '%s\n' "$*" >&2
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

run_cmd() {
  if $QUIET; then
    "$@" >/dev/null
  else
    "$@"
  fi
}

run_cmd_no_check() {
  if $QUIET; then
    "$@" >/dev/null || true
  else
    "$@" || true
  fi
}

run_cmd_status() {
  if $QUIET; then
    "$@" >/dev/null
  else
    "$@"
  fi
}

has_required() {
  local base="$1"
  shift
  local name
  for name in "$@"; do
    if [[ ! -e "$base/$name" ]]; then
      return 1
    fi
  done
  return 0
}

resolve_backup_root() {
  local base_root="$1"
  shift
  local required=("$@")
  if has_required "$base_root" "${required[@]}"; then
    printf '%s\n' "$base_root"
    return 0
  fi
  local candidate
  for candidate in "$base_root"/*/; do
    if [[ ! -d "$candidate" ]]; then
      continue
    fi
    if has_required "${candidate%/}" "${required[@]}"; then
      printf '%s\n' "${candidate%/}"
      return 0
    fi
  done
  return 1
}

main() {
  # Fixed user + mount layout for this machine.
  local user="ralexander"
  local usb_label="${BKP_USB_LABEL:-netac}"
  local usb_user="${SUDO_USER:-${USER:-$user}}"
  local user_home
  user_home="$(getent passwd "$user" | cut -d: -f6)"
  if [[ -z "$user_home" ]]; then
    user_home="/home/$user"
  fi
  local usb_mount="/run/media/${usb_user}/${usb_label}"
  local base_root="${usb_mount}/START"
  local dirs=("Documents" "Pictures" "Obsidian" "Working" "Shared" "VM" "Code" "Videos")

  for cmd in rsync mountpoint; do
    if ! command_exists "$cmd"; then
      err "ERROR: ${cmd} not found."
      exit 1
    fi
  done

  if ! mountpoint -q "$usb_mount"; then
    err "ERROR: ${usb_mount} is not a mountpoint. Is the USB plugged in and mounted?"
    exit 1
  fi

  # Locate the backup root (supports direct START or newest subdir).
  local usb
  if ! usb="$(resolve_backup_root "$base_root" "home" "dots")"; then
    err "ERROR: backup root not found under ${base_root}"
    exit 1
  fi

  if [[ ! -d "$usb/home" ]]; then
    err "ERROR: ${usb}/home does not exist"
    exit 1
  fi
  if [[ ! -d "$usb/dots" ]]; then
    err "ERROR: ${usb}/dots does not exist"
    exit 1
  fi
  local srv="${usb}/Srv"
  if [[ ! -d "$srv" ]]; then
    err "ERROR: ${srv} does not exist"
    exit 1
  fi

  status "Restore start: $(date '+%Y-%m-%dT%H:%M:%S')"
  progress "Pre-flight checks"

  # Local backup of overwritten configs.
  local backup_dir="${usb}/logs/backups/restore-main-$(date '+%Y%m%d%H%M%S')"
  mkdir -p "$backup_dir"

  # Ensure target directories exist before rsync/copy.
  mkdir -p "${user_home}/.config/Thunar"
  mkdir -p "${user_home}/.config/com.ml4w.hyprlandsettings"
  mkdir -p "${user_home}/.local/share/icons"

  # Backup and patch a few system/user configs.
  local hypr_conf="${user_home}/.config/hypr/hyprland.conf"
  if [[ -f "$hypr_conf" ]]; then
    run_cmd_no_check sudo cp -a "$hypr_conf" "${backup_dir}/hyprland.conf"
    run_cmd_no_check sudo sed -i "s|^autogenerated = 1|# autogenerated = 1|" "$hypr_conf"
  fi

  local sddm_conf="/usr/lib/sddm/sddm.conf.d/default.conf"
  if [[ -f "$sddm_conf" ]]; then
    run_cmd_no_check sudo cp -a "$sddm_conf" "${backup_dir}/sddm.default.conf"
    run_cmd_no_check sudo sed -i "s|^User=|User=${user}|" "$sddm_conf"
  fi

  # Thunar custom actions.
  progress "Thunar"
  local uca_src="${usb}/dots/uca.xml"
  local uca_restored="no"
  if [[ -f "$uca_src" ]]; then
    run_cmd rsync -arh --quiet "$uca_src" "${user_home}/.config/Thunar"
    uca_restored="yes"
  fi

  # Restore main user folders.
  local restored_dirs=()
  progress "User directories"
  local d
  for d in "${dirs[@]}"; do
    local src="${usb}/home/${d}"
    if [[ -e "$src" ]]; then
      run_cmd rsync -arh --quiet "$src" "$user_home"
      restored_dirs+=("$d")
    fi
  done

  # Restore cursor, icons, and themes.
  local cursor_restored="no"
  progress "Icons and themes"
  local cursor_src="${usb}/home/LyraX-cursors"
  if [[ -d "$cursor_src" ]]; then
    run_cmd rsync -arh --quiet "$cursor_src" "${user_home}/.local/share/icons"
    cursor_restored="yes"
  fi

  local icons_restored="no"
  local themes_restored="no"
  if run_cmd_status rsync -arh --quiet "${usb}/home/.icons" "$user_home"; then
    icons_restored="yes"
  fi
  if run_cmd_status rsync -arh --quiet "${usb}/home/.themes" "$user_home"; then
    themes_restored="yes"
  fi

  # Restore dotfiles to home.
  local dots_restored="no"
  progress "Dotfiles"
  if run_cmd_status rsync -arh --quiet "${usb}/dots" "$user_home"; then
    dots_restored="yes"
  fi

  # Run fonts install script if present.
  local fonts_installed="no"
  progress "Fonts"
  local fonts_script="${usb_mount}/BIG/fonts/install.sh"
  if [[ ! -f "$fonts_script" ]]; then
    fonts_script="${user_home}/Shared/fonts/install.sh"
  fi
  if [[ -f "$fonts_script" && -x "$fonts_script" ]]; then
    if run_cmd_status bash "$fonts_script"; then
      fonts_installed="yes"
    fi
  else
    err "Font install script not found or not executable: ${fonts_script}"
  fi

  # Install yay if needed (Arch only).
  local yay_installed="no"
  progress "Yay"
  if command_exists pacman; then
    run_cmd_no_check sudo pacman -S --needed --noconfirm git base-devel
    local yay_dir="${user_home}/yay"
    if [[ ! -d "$yay_dir" ]]; then
      run_cmd_no_check git clone https://aur.archlinux.org/yay.git "$yay_dir"
    fi
    if run_cmd_status sudo -u "$user" bash -lc "cd \"$yay_dir\" && makepkg -si --noconfirm"; then
      yay_installed="yes"
    fi
  else
    err "pacman not found; skipping yay install."
  fi

  # Install ML4W tool via Flatpak.
  progress "ML4W Dotfiles Installer"
  local ml4w_installed="no"
  if flatpak install flathub com.ml4w.dotfilesinstaller; then
    ml4w_installed="yes"
  fi

  status "Restore done."
  status "UCA restored: ${uca_restored}"
  if [[ ${#restored_dirs[@]} -gt 0 ]]; then
    status "Dirs restored: $(IFS=', '; echo "${restored_dirs[*]}")"
  else
    status "Dirs restored: none"
  fi
  status "Cursor restored: ${cursor_restored}"
  status "Icons restored: ${icons_restored}"
  status "Themes restored: ${themes_restored}"
  status "Dotfiles restored: ${dots_restored}"
  status "Fonts installed: ${fonts_installed}"
  status "Yay installed: ${yay_installed}"
  status "ML4W installed: ${ml4w_installed}"
  status "Target: ${usb}"
}

main "$@"
