#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Restore main user files and dotfiles from the v2 USB layout.

USB_LABEL="${BKP_USB_LABEL:-netac}"
USB="/run/media/$USER/$USB_LABEL"
RUN_AS_USER="ralexander"
USER_HOME="$(getent passwd "$RUN_AS_USER" | cut -d: -f6)"

DIRS=(Documents Pictures Obsidian Working Shared VM Code Videos)

TOTAL_STEPS=6
STEP=0
status() { printf '%s\n' "$*" >/dev/tty; }
progress() {
  STEP=$((STEP + 1))
  printf '[%d/%d] %s\n' "$STEP" "$TOTAL_STEPS" "$*" >/dev/tty
}
err() { printf '[!] %s\n' "$*" >/dev/tty; }

LOG_FILE="/tmp/restore-main-v2-$(date +%Y%m%d%H%M%S).log"
exec >"$LOG_FILE" 2> >(tee -a "$LOG_FILE" >/dev/tty)
status "Restore start: $(date -Is)"
status "Log: $LOG_FILE"

if ! command -v rsync >/dev/null 2>&1; then
  err "ERROR: rsync not found."
  exit 1
fi
if ! command -v mountpoint >/dev/null 2>&1; then
  err "ERROR: mountpoint not found."
  exit 1
fi
if ! mountpoint -q "$USB"; then
  err "ERROR: $USB is not a mountpoint. Is the USB plugged in and mounted?"
  exit 1
fi

if [[ ! -d "$USB/home" ]]; then
  err "ERROR: $USB/home does not exist"
  exit 1
fi
if [[ ! -d "$USB/dots" ]]; then
  err "ERROR: $USB/dots does not exist"
  exit 1
fi

mkdir -p "$USER_HOME/.config/Thunar"
mkdir -p "$USER_HOME/.config/com.ml4w.hyprlandsettings"
mkdir -p "$USER_HOME/.local/share/icons"

# Disable autogenerated line (if present)
if [[ -f "$USER_HOME/.config/hypr/hyprland.conf" ]]; then
  sed -i 's|^autogenerated = 1|# autogenerated = 1|' "$USER_HOME/.config/hypr/hyprland.conf"
fi

# SDDM autologin user
if [[ -f /usr/lib/sddm/sddm.conf.d/default.conf ]]; then
  sudo sed -i "/^User=/s//User=$RUN_AS_USER/" /usr/lib/sddm/sddm.conf.d/default.conf
fi

# Thunar custom actions XML
progress "Pre-flight + Thunar"
UCA_RESTORED="no"
if [[ -f "$USB/dots/uca.xml" ]]; then
  rsync -arh --quiet "$USB/dots/uca.xml" "$USER_HOME/.config/Thunar/"
  UCA_RESTORED="yes"
fi

# Main home directories
progress "User directories"
RESTORED_DIRS=()
for d in "${DIRS[@]}"; do
  if [[ -e "$USB/home/$d" ]]; then
    rsync -arh --quiet "$USB/home/$d" "$USER_HOME/"
    RESTORED_DIRS+=("$d")
  fi
done

# Icons & themes
progress "Icons and themes"
CURSOR_RESTORED="no"
if [[ -d "$USB/home/LyraX-cursors" ]]; then
  rsync -arh --quiet "$USB/home/LyraX-cursors" "$USER_HOME/.local/share/icons/"
  CURSOR_RESTORED="yes"
fi
ICONS_RESTORED="no"
THEMES_RESTORED="no"
if rsync -arh --quiet "$USB/home"/.icons "$USER_HOME/" 2>/dev/null; then
  ICONS_RESTORED="yes"
fi
if rsync -arh --quiet "$USB/home"/.themes "$USER_HOME/" 2>/dev/null; then
  THEMES_RESTORED="yes"
fi

# Dotfiles tree (folder into $USER_HOME)
progress "Dotfiles"
DOTS_RESTORED="no"
if rsync -arh --quiet "$USB/dots" "$USER_HOME/"; then
  DOTS_RESTORED="yes"
fi

# Font install
progress "Fonts"
FONTS_INSTALLED="no"
if [[ -x "$USER_HOME/Shared/fonts/install.sh" ]]; then
  if bash "$USER_HOME/Shared/fonts/install.sh"; then
    FONTS_INSTALLED="yes"
  fi
else
  err "Font install script not found or not executable: $USER_HOME/Shared/fonts/install.sh"
fi

# Install yay
progress "Yay"
YAY_INSTALLED="no"
if command -v pacman >/dev/null 2>&1; then
  sudo pacman -S --needed --noconfirm git base-devel
  if [[ ! -d "$USER_HOME/yay" ]]; then
    git clone https://aur.archlinux.org/yay.git "$USER_HOME/yay"
  fi
  if (cd "$USER_HOME/yay" && sudo -u "$RUN_AS_USER" makepkg -si --noconfirm); then
    YAY_INSTALLED="yes"
  fi
else
  err "pacman not found; skipping yay install."
fi

status "Restore done."
