#!/usr/bin/env python3
import os
import pwd
import shutil
import subprocess
import sys
import time


QUIET = True
TOTAL_STEPS = 8
STEP = 0


def run(cmd, check=True):
    if QUIET:
        return subprocess.run(cmd, check=check, stdout=subprocess.DEVNULL)
    return subprocess.run(cmd, check=check)


def command_exists(cmd):
    return shutil.which(cmd) is not None


def status(msg):
    print(msg)


def progress(msg):
    global STEP
    STEP += 1
    status(f"[{STEP}/{TOTAL_STEPS}] {msg}")


def err(msg):
    print(msg, file=sys.stderr)


def run_interactive(cmd, check=True):
    return subprocess.run(cmd, check=check)


def resolve_backup_root(base_root, required):
    def has_required(path):
        return all(
            os.path.exists(os.path.join(path, name)) for name in required
        )

    if has_required(base_root):
        return base_root
    try:
        candidates = [
            os.path.join(base_root, name)
            for name in os.listdir(base_root)
            if os.path.isdir(os.path.join(base_root, name))
        ]
    except OSError:
        return None
    candidates.sort(key=os.path.getmtime, reverse=True)
    for candidate in candidates:
        if has_required(candidate):
            return candidate
    return None


def main():
    # Fixed user + mount layout for this machine.
    user = "ralexander"
    usb_label = os.environ.get("BKP_USB_LABEL", "netac")
    usb_user = os.environ.get("SUDO_USER") or os.environ.get("USER") or user
    user_home = pwd.getpwnam(user).pw_dir
    usb_mount = f"/run/media/{usb_user}/{usb_label}"
    base_root = os.path.join(usb_mount, "START")

    dirs = [
        "Documents",
        "Pictures",
        "Obsidian",
        "Working",
        "Shared",
        "VM",
        "Code",
        "Videos",
    ]

    for cmd in ["rsync", "mountpoint"]:
        if not command_exists(cmd):
            err(f"ERROR: {cmd} not found.")
            sys.exit(1)

    if run(["mountpoint", "-q", usb_mount], check=False).returncode != 0:
        err(
            f"ERROR: {usb_mount} is not a mountpoint. "
            "Is the USB plugged in and mounted?"
        )
        sys.exit(1)

    # Locate the backup root (supports direct START or newest subdir).
    usb = resolve_backup_root(base_root, ["home", "dots"])
    if not usb:
        err(f"ERROR: backup root not found under {base_root}")
        sys.exit(1)

    if not os.path.isdir(os.path.join(usb, "home")):
        err(f"ERROR: {usb}/home does not exist")
        sys.exit(1)
    if not os.path.isdir(os.path.join(usb, "dots")):
        err(f"ERROR: {usb}/dots does not exist")
        sys.exit(1)
    srv = os.path.join(usb, "Srv")
    if not os.path.isdir(srv):
        err(f"ERROR: {srv} does not exist")
        sys.exit(1)

    status(f"Restore start: {time.strftime('%Y-%m-%dT%H:%M:%S')}")
    progress("Pre-flight checks")

    # Local backup of overwritten configs.
    backup_dir = os.path.join(
        usb, "logs", "backups", f"restore-main-{time.strftime('%Y%m%d%H%M%S')}"
    )
    os.makedirs(backup_dir, exist_ok=True)

    # Ensure target directories exist before rsync/copy.
    os.makedirs(os.path.join(user_home, ".config", "Thunar"), exist_ok=True)
    os.makedirs(
        os.path.join(user_home, ".config", "com.ml4w.hyprlandsettings"),
        exist_ok=True,
    )
    os.makedirs(
        os.path.join(user_home, ".local", "share", "icons"), exist_ok=True
    )

    # Backup and patch a few system/user configs before overwriting.
    hypr_conf = os.path.join(user_home, ".config", "hypr", "hyprland.conf")
    if os.path.isfile(hypr_conf):
        run(
            [
                "sudo",
                "cp",
                "-a",
                hypr_conf,
                os.path.join(backup_dir, "hyprland.conf"),
            ],
            check=False,
        )
        run(
            [
                "sed",
                "-i",
                "s|^autogenerated = 1|# autogenerated = 1|",
                hypr_conf,
            ],
            check=False,
        )

    sddm_conf = "/usr/lib/sddm/sddm.conf.d/default.conf"
    if os.path.isfile(sddm_conf):
        run(
            [
                "sudo",
                "cp",
                "-a",
                sddm_conf,
                os.path.join(backup_dir, "sddm.default.conf"),
            ],
            check=False,
        )
        run(
            ["sudo", "sed", "-i", f"/^User=/s//User={user}/", sddm_conf],
            check=False,
        )

    # Thunar custom actions.
    progress("Thunar")
    uca_src = os.path.join(usb, "dots", "uca.xml")
    uca_restored = "no"
    if os.path.isfile(uca_src):
        run(
            [
                "rsync",
                "-arh",
                "--quiet",
                uca_src,
                os.path.join(user_home, ".config", "Thunar"),
            ]
        )
        uca_restored = "yes"

    # Restore main user folders.
    restored_dirs = []
    progress("User directories")
    for d in dirs:
        src = os.path.join(usb, "home", d)
        if os.path.exists(src):
            run(["rsync", "-arh", "--quiet", src, user_home])
            restored_dirs.append(d)

    # Restore cursor, icons, and themes.
    cursor_restored = "no"
    progress("Icons and themes")
    cursor_src = os.path.join(usb, "home", "LyraX-cursors")
    if os.path.isdir(cursor_src):
        run(
            [
                "rsync",
                "-arh",
                "--quiet",
                cursor_src,
                os.path.join(user_home, ".local", "share", "icons"),
            ]
        )
        cursor_restored = "yes"

    icons_restored = "no"
    themes_restored = "no"
    if (
        run(
            [
                "rsync",
                "-arh",
                "--quiet",
                os.path.join(usb, "home", ".icons"),
                user_home,
            ],
            check=False,
        ).returncode
        == 0
    ):
        icons_restored = "yes"
    if (
        run(
            [
                "rsync",
                "-arh",
                "--quiet",
                os.path.join(usb, "home", ".themes"),
                user_home,
            ],
            check=False,
        ).returncode
        == 0
    ):
        themes_restored = "yes"

    # Restore dotfiles to home.
    dots_restored = "no"
    progress("Dotfiles")
    if (
        run(
            ["rsync", "-arh", "--quiet", os.path.join(usb, "dots"), user_home],
            check=False,
        ).returncode
        == 0
    ):
        dots_restored = "yes"

    # Run fonts install script if present.
    fonts_installed = "no"
    progress("Fonts")
    fonts_script = os.path.join(usb_mount, "BIG", "fonts", "install.sh")
    if not os.path.isfile(fonts_script):
        fonts_script = os.path.join(user_home, "Shared", "fonts", "install.sh")
    if os.path.isfile(fonts_script) and os.access(fonts_script, os.X_OK):
        if run(["bash", fonts_script], check=False).returncode == 0:
            fonts_installed = "yes"
        else:
            err("Fonts install failed; continuing.")
    else:
        err(f"Font install script not found or not executable: {fonts_script}")

    # Install yay if needed (Arch only). Failures are non-fatal.
    yay_installed = "no"
    progress("Yay")
    if command_exists("pacman"):
        run(
            [
                "sudo",
                "pacman",
                "-S",
                "--needed",
                "--noconfirm",
                "git",
                "base-devel",
            ],
            check=False,
        )
        yay_dir = os.path.join(user_home, "yay")
        if not os.path.isdir(yay_dir):
            run(
                ["git", "clone", "https://aur.archlinux.org/yay.git", yay_dir],
                check=False,
            )
        if (
            run(
                [
                    "sudo",
                    "-u",
                    user,
                    "bash",
                    "-lc",
                    f"cd {yay_dir} && makepkg -si --noconfirm",
                ],
                check=False,
            ).returncode
            == 0
        ):
            yay_installed = "yes"
        else:
            err("Yay install failed; continuing.")
    else:
        err("pacman not found; skipping yay install.")

    # Install ML4W tool via Flatpak.
    progress("ML4W Dotfiles Installer")
    ml4w_installed = "no"
    if command_exists("flatpak"):
        install_rc = run_interactive(
            [
                "flatpak",
                "install",
                "--user",
                "--noninteractive",
                "flathub",
                "com.ml4w.dotfilesinstaller",
            ],
            check=False,
        ).returncode
        if install_rc == 0:
            ml4w_installed = "yes"
        else:
            err("ML4W install skipped or failed.")
    else:
        err("flatpak not found; skipping ML4W install.")

    status("Restore done.")
    status(f"UCA restored: {uca_restored}")
    status(
        "Dirs restored: "
        f"{', '.join(restored_dirs) if restored_dirs else 'none'}"
    )
    status(f"Cursor restored: {cursor_restored}")
    status(f"Icons restored: {icons_restored}")
    status(f"Themes restored: {themes_restored}")
    status(f"Dotfiles restored: {dots_restored}")
    status(f"Fonts installed: {fonts_installed}")
    status(f"Yay installed: {yay_installed}")
    status(f"ML4W installed: {ml4w_installed}")
    status(f"Target: {usb}")


if __name__ == "__main__":
    main()
