#!/usr/bin/env bash
set -euo pipefail

# Main restore shell script.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
user_name="${USER:-$(id -un)}"
confirm_restore=false
show_banner=true
auto_yes=false

# Parse flags.
while [[ $# -gt 0 ]]; do
	case "$1" in
	--no-banner)
		show_banner=false
		shift
		;;
	--yes)
		auto_yes=true
		shift
		;;
	--confirm)
		confirm_restore=true
		shift
		;;
	*)
		shift
		;;
	esac
done

# Banner.
if $show_banner; then
	cat <<'EOF'
Restore MAIN
Options:
  --confirm   Ask before destructive restore
  --yes       Auto-confirm destructive prompt
  --no-banner Skip this prompt
EOF
	read -r -p "Press Enter to continue..." _
fi

# Required tools.
required_cmds=(rsync)
for required_cmd in "${required_cmds[@]}"; do
	if ! command -v "$required_cmd" >/dev/null 2>&1; then
		echo "Missing required command: ${required_cmd}" >&2
		exit 1
	fi
done

# Hyprland config tweak.
hypr_conf="/home/${user_name}/.config/hypr/hyprland.conf"
if [[ -f "$hypr_conf" ]]; then
	sed -i 's/^autogenerated = 1$/# autogenerated = 1/' "$hypr_conf" || true
fi

# Confirm destructive restore if requested.
if $confirm_restore; then
	if $auto_yes; then
		answer="y"
	else
		read -r -p "This restore may delete files in /home/${user_name}. Continue? [y/N]: " answer
	fi
	if [[ ! "$answer" =~ ^[yY]$ ]]; then
		echo "Restore cancelled."
		exit 0
	fi
fi

# Sources list.
sources=(
	"Documents"
	"Downloads"
	"Pictures"
	"Obsidian"
	"Working"
	"Shared"
	"VM"
	"Code"
	"Videos"
	".icons"
	".themes"
	".local/share/icons"
	".ssh"
)

# Rsync defaults for restore.
rsync_opts=(
	-aAXH
	--numeric-ids
	--sparse
	--delete-delay
	--info=stats1
)

rsync_failures=0

run_rsync() {
	local src="$1"
	local dest="$2"
	echo "Restoring: ${src} -> ${dest}"
	rsync "${rsync_opts[@]}" "$src" "$dest"
	rc=$?
	if [[ $rc -eq 23 || $rc -eq 24 ]]; then
		echo "rsync returned partial transfer code ${rc}; continuing." >&2
		return 0
	fi
	if [[ $rc -ne 0 ]]; then
		echo "rsync failed with code ${rc} for ${src}" >&2
		rsync_failures=$((rsync_failures + 1))
		return 0
	fi
	return 0
}

sources_total=0
sources_skipped=0

font_install_checked=false

run_font_install() {
	if $font_install_checked; then
		return
	fi
	font_install_checked=true
	font_install="/run/media/${user_name}/BIG/fonts/install.sh"
	if [[ -f "$font_install" ]]; then
		echo "Running font installer: ${font_install}"
		bash "$font_install" || true
	else
		echo "Font installer not found at ${font_install}; skipping."
	fi

	if command -v flatpak >/dev/null 2>&1; then
		if ! flatpak info com.ml4w.dotfilesinstaller >/dev/null 2>&1; then
			flatpak install flathub com.ml4w.dotfilesinstaller || true
		fi
	else
		echo "flatpak not found; skipping com.ml4w.dotfilesinstaller install."
	fi
}

# Restore each source.
for name in "${sources[@]}"; do
	src="${script_dir}/${name}"
	if [[ ! -e "$src" ]]; then
		echo "Skipping missing source: ${src}"
		sources_skipped=$((sources_skipped + 1))
		continue
	fi
	sources_total=$((sources_total + 1))
	case "$name" in
	".local/share/icons")
		run_rsync "$src" "/home/${user_name}/.local/share/"
		;;
	".ssh")
		run_font_install
		run_rsync "$src" "/home/${user_name}/"
		if [[ -d "/home/${user_name}/.ssh" ]]; then
			chmod 700 "/home/${user_name}/.ssh" || true
			find "/home/${user_name}/.ssh" -type f -name "*.pub" -exec chmod 644 {} + || true
			find "/home/${user_name}/.ssh" -type f ! -name "*.pub" -exec chmod 600 {} + || true
		fi
		;;
	*)
		run_rsync "$src" "/home/${user_name}/"
		;;
	esac
done

# SDDM user update (sudo).
sddm_conf="/usr/lib/sddm/sddm.conf.d/default.conf"
if [[ -f "$sddm_conf" ]]; then
	if command -v sudo >/dev/null 2>&1; then
		sudo sed -i "s/^User=.*/User=${user_name}/" "$sddm_conf" || true
	else
		echo "sudo not found; skipping SDDM User update."
	fi
fi

echo "Restore completed from: ${script_dir}"
echo "Summary: sources=${sources_total}, skipped=${sources_skipped}, rsync_failures=${rsync_failures}"
if ((rsync_failures > 0)); then
	exit 1
fi
