#!/usr/bin/env python3
"""Main restore Python script."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path


def run_rsync(args: Sequence[str]) -> None:
    """Run rsync and normalize partial transfer codes."""
    result = subprocess.run(
        args,
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.stderr:
        for line in result.stderr.splitlines():
            print(f"rsync: {line}", file=sys.stderr)
    if result.returncode in {23, 24}:
        print(
            f"rsync returned partial transfer code {result.returncode}; continuing.",
            file=sys.stderr,
        )
        return
    if result.returncode != 0:
        raise RuntimeError(f"rsync failed with code {result.returncode}")


def main() -> int:
    # Banner and flags.
    user_name = os.environ.get("USER") or os.getlogin()
    show_banner = "--no-banner" not in sys.argv
    auto_yes = "--yes" in sys.argv
    if show_banner:
        print("""Restore MAIN
Options:
  --confirm   Ask before destructive restore
  --yes       Auto-confirm destructive prompt
  --no-banner Skip this prompt
""")
        input("Press Enter to continue...")
    confirm_restore = "--confirm" in sys.argv
    # Validate required tools.
    if shutil.which("rsync") is None:
        print("Missing required command: rsync", file=sys.stderr)
        return 1

    # Hyprland config tweak.
    hypr_conf = Path(f"/home/{user_name}/.config/hypr/hyprland.conf")
    if hypr_conf.is_file():
        try:
            content = hypr_conf.read_text(encoding="utf-8")
            updated = content.replace("autogenerated = 1", "# autogenerated = 1")
            if updated != content:
                hypr_conf.write_text(updated, encoding="utf-8")
        except OSError:
            pass

    # SDDM user update (sudo).
    sddm_conf = Path("/usr/lib/sddm/sddm.conf.d/default.conf")
    if sddm_conf.is_file():
        if shutil.which("sudo") is not None:
            subprocess.run(
                ["sudo", "sed", "-i", f"s/^User=.*/User={user_name}/", str(sddm_conf)],
                check=False,
            )
        else:
            print("sudo not found; skipping SDDM User update.")

    # Confirm destructive restore if requested.
    if confirm_restore:
        if auto_yes:
            answer = "y"
        else:
            answer = input(
                f"This restore may delete files in /home/{user_name}. Continue? [y/N]: "
            ).strip()
        if answer.lower() != "y":
            print("Restore cancelled.")
            return 0

    script_dir = Path(__file__).resolve().parent
    sources = [
        "Documents",
        "Downloads",
        "Pictures",
        "Obsidian",
        "Working",
        "Shared",
        "VM",
        "Code",
        "Videos",
        ".icons",
        ".themes",
        ".local/share/icons",
        ".ssh",
    ]

    # Rsync defaults for restore.
    rsync_opts = [
        "rsync",
        "-aAXH",
        "--numeric-ids",
        "--sparse",
        "--delete-delay",
        "--info=stats1",
    ]

    rsync_failures = 0
    sources_total = 0
    sources_skipped = 0

    font_install_checked = False
    font_install_run = False

    def run_font_install() -> None:
        """Install fonts + optional dotfiles installer."""
        nonlocal font_install_checked, font_install_run
        if font_install_checked:
            return
        font_install_checked = True
        font_install = Path(f"/run/media/{user_name}/BIG/fonts/install.sh")
        if font_install.is_file():
            print(f"Running font installer: {font_install}")
            try:
                subprocess.run(["bash", str(font_install)], check=False)
                font_install_run = True
            except OSError:
                pass
        else:
            print(f"Font installer not found at {font_install}; skipping.")

        if shutil.which("flatpak") is not None:
            info = subprocess.run(
                ["flatpak", "info", "com.ml4w.dotfilesinstaller"],
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            if info.returncode != 0:
                subprocess.run(
                    ["flatpak", "install", "flathub", "com.ml4w.dotfilesinstaller"],
                    check=False,
                )
        else:
            print("flatpak not found; skipping com.ml4w.dotfilesinstaller install.")

    # Restore each source.
    for name in sources:
        src = script_dir / name
        if not src.exists():
            print(f"Skipping missing source: {src}")
            sources_skipped += 1
            continue
        sources_total += 1
        dest = Path(f"/home/{user_name}/")
        if name == ".local/share/icons":
            dest = Path(f"/home/{user_name}/.local/share/")
        print(f"Restoring: {src} -> {dest}")
        try:
            if name == ".ssh":
                run_font_install()
            run_rsync([*rsync_opts, str(src), str(dest)])
            if name == ".ssh":
                ssh_dir = Path(f"/home/{user_name}/.ssh")
                if ssh_dir.is_dir():
                    ssh_dir.chmod(0o700)
                    for path in ssh_dir.rglob("*"):
                        if path.is_file():
                            if path.name.endswith(".pub"):
                                path.chmod(0o644)
                            else:
                                path.chmod(0o600)
        except RuntimeError as exc:
            print(str(exc), file=sys.stderr)
            rsync_failures += 1

    print(f"Restore completed from: {script_dir}")
    summary = (
        f"Summary: sources={sources_total}, skipped={sources_skipped}, "
        f"rsync_failures={rsync_failures}"
    )
    print(summary)
    return 1 if rsync_failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
