#!/usr/bin/env python3
import getpass
import os
import pwd
import shutil
import subprocess
import sys


def run(cmd, check=True):
    return subprocess.run(cmd, check=check)


def command_exists(cmd):
    return shutil.which(cmd) is not None


def main():
    usb_label = os.environ.get("BKP_USB_LABEL", "netac")
    user = os.environ.get("SUDO_USER") or os.environ.get("USER") or getpass.getuser()
    user_home = pwd.getpwnam(user).pw_dir
    usb = f"/run/media/{user}/{usb_label}"
    srv = os.path.join(usb, "Srv")

    dirs = ["Documents", "Pictures", "Obsidian", "Working", "Shared", "VM", "Code", "Videos"]

    for cmd in ["rsync", "mountpoint"]:
        if not command_exists(cmd):
            print(f"ERROR: {cmd} not found.")
            sys.exit(1)

    if run(["mountpoint", "-q", usb], check=False).returncode != 0:
        print(f"ERROR: {usb} is not a mountpoint. Is the USB plugged in and mounted?")
        sys.exit(1)

    if not os.path.isdir(os.path.join(usb, "home")):
        print(f"ERROR: {usb}/home does not exist")
        sys.exit(1)
    if not os.path.isdir(os.path.join(usb, "dots")):
        print(f"ERROR: {usb}/dots does not exist")
        sys.exit(1)
    if not os.path.isdir(srv):
        print(f"ERROR: {srv} does not exist")
        sys.exit(1)

    os.makedirs(os.path.join(user_home, ".config", "Thunar"), exist_ok=True)
    os.makedirs(os.path.join(user_home, ".config", "com.ml4w.hyprlandsettings"), exist_ok=True)
    os.makedirs(os.path.join(user_home, ".local", "share", "icons"), exist_ok=True)

    hypr_conf = os.path.join(user_home, ".config", "hypr", "hyprland.conf")
    if os.path.isfile(hypr_conf):
        run(["sed", "-i", "s|^autogenerated = 1|# autogenerated = 1|", hypr_conf], check=False)

    sddm_conf = "/usr/lib/sddm/sddm.conf.d/default.conf"
    if os.path.isfile(sddm_conf):
        run(["sudo", "sed", "-i", f"/^User=/s//User={user}/", sddm_conf], check=False)

    uca_src = os.path.join(usb, "dots", "uca.xml")
    uca_restored = "no"
    if os.path.isfile(uca_src):
        run(["rsync", "-Prah", uca_src, os.path.join(user_home, ".config", "Thunar")])
        uca_restored = "yes"

    restored_dirs = []
    for d in dirs:
        src = os.path.join(usb, "home", d)
        if os.path.exists(src):
            run(["rsync", "-Prah", src, user_home])
            restored_dirs.append(d)

    cursor_restored = "no"
    cursor_src = os.path.join(usb, "home", "LyraX-cursors")
    if os.path.isdir(cursor_src):
        run(["rsync", "-Prah", cursor_src, os.path.join(user_home, ".local", "share", "icons")])
        cursor_restored = "yes"

    icons_restored = "no"
    themes_restored = "no"
    if run(["rsync", "-Prah", os.path.join(usb, "home", ".icons"), user_home], check=False).returncode == 0:
        icons_restored = "yes"
    if run(["rsync", "-Prah", os.path.join(usb, "home", ".themes"), user_home], check=False).returncode == 0:
        themes_restored = "yes"

    dots_restored = "no"
    if run(["rsync", "-Prah", f"{os.path.join(usb, 'dots')}/", user_home], check=False).returncode == 0:
        dots_restored = "yes"

    fonts_installed = "no"
    fonts_script = os.path.join(user_home, "Shared", "fonts", "install.sh")
    if os.path.isfile(fonts_script) and os.access(fonts_script, os.X_OK):
        if run(["bash", fonts_script], check=False).returncode == 0:
            fonts_installed = "yes"
    else:
        print(f"Font install script not found or not executable: {fonts_script}")

    yay_installed = "no"
    if command_exists("pacman"):
        run(["sudo", "pacman", "-S", "--needed", "--noconfirm", "git", "base-devel"], check=False)
        yay_dir = os.path.join(user_home, "yay")
        if not os.path.isdir(yay_dir):
            run(["git", "clone", "https://aur.archlinux.org/yay.git", yay_dir], check=False)
        if run(["sudo", "-u", user, "bash", "-lc", f"cd {yay_dir} && makepkg -si --noconfirm"], check=False).returncode == 0:
            yay_installed = "yes"
    else:
        print("pacman not found; skipping yay install.")

    print("Main restore done.")
    print(f"Restored directories: {' '.join(restored_dirs) if restored_dirs else 'none'}")
    print(f"Dotfiles restored: {dots_restored}")
    print(f"Thunar uca.xml restored: {uca_restored}")
    print(f"Cursor pack restored: {cursor_restored}")
    print(f".icons restored: {icons_restored}")
    print(f".themes restored: {themes_restored}")
    print(f"Fonts installed: {fonts_installed}")
    print(f"Yay installed: {yay_installed}")


if __name__ == "__main__":
    main()
