#!/usr/bin/env python3
import os
import pwd
import shutil
import subprocess
import sys
import time


LOG_FH = None
QUIET = True
TOTAL_STEPS = 7
STEP = 0


def run(cmd, check=True):
    if QUIET and LOG_FH:
        return subprocess.run(cmd, check=check, stdout=LOG_FH, stderr=LOG_FH)
    return subprocess.run(cmd, check=check)


def command_exists(cmd):
    return shutil.which(cmd) is not None


def log(msg):
    if LOG_FH:
        LOG_FH.write(msg + "\n")
        LOG_FH.flush()


def status(msg):
    print(msg)
    log(msg)


def progress(msg):
    global STEP
    STEP += 1
    status(f"[{STEP}/{TOTAL_STEPS}] {msg}")


def err(msg):
    print(msg, file=sys.stderr)
    log(msg)

def resolve_backup_root(base_root, required):
    def has_required(path):
        return all(os.path.exists(os.path.join(path, name)) for name in required)
    if has_required(base_root):
        return base_root
    try:
        candidates = [
            os.path.join(base_root, name)
            for name in os.listdir(base_root)
            if os.path.isdir(os.path.join(base_root, name))
        ]
    except OSError:
        return None
    candidates.sort(key=os.path.getmtime, reverse=True)
    for candidate in candidates:
        if has_required(candidate):
            return candidate
    return None

def main():
    user = "ralexander"
    usb_label = os.environ.get("BKP_USB_LABEL", "netac")
    usb_user = os.environ.get("SUDO_USER") or os.environ.get("USER") or user
    user_home = pwd.getpwnam(user).pw_dir
    usb_mount = f"/run/media/{usb_user}/{usb_label}"
    base_root = os.path.join(usb_mount, "START")

    dirs = ["Documents", "Pictures", "Obsidian", "Working", "Shared", "VM", "Code", "Videos"]

    for cmd in ["rsync", "mountpoint"]:
        if not command_exists(cmd):
            err(f"ERROR: {cmd} not found.")
            sys.exit(1)

    if run(["mountpoint", "-q", usb_mount], check=False).returncode != 0:
        err(f"ERROR: {usb_mount} is not a mountpoint. Is the USB plugged in and mounted?")
        sys.exit(1)

    usb = resolve_backup_root(base_root, ["home", "dots"])
    if not usb:
        err(f"ERROR: backup root not found under {base_root}")
        sys.exit(1)

    if not os.path.isdir(os.path.join(usb, "home")):
        err(f"ERROR: {usb}/home does not exist")
        sys.exit(1)
    if not os.path.isdir(os.path.join(usb, "dots")):
        err(f"ERROR: {usb}/dots does not exist")
        sys.exit(1)
    srv = os.path.join(usb, "Srv")
    if not os.path.isdir(srv):
        err(f"ERROR: {srv} does not exist")
        sys.exit(1)

    log_dir = os.path.join(usb, "logs")
    try:
        os.makedirs(log_dir, exist_ok=True)
        log_path = os.path.join(log_dir, f"restore-main-{time.strftime('%Y%m%d%H%M%S')}.log")
        global LOG_FH
        LOG_FH = open(log_path, "a", encoding="utf-8", errors="replace")
    except OSError as exc:
        print(f"ERROR: unable to open log file in {log_dir}: {exc}", file=sys.stderr)
        sys.exit(1)

    status(f"Restore start: {time.strftime('%Y-%m-%dT%H:%M:%S')}")
    status(f"Log: {log_path}")
    progress("Pre-flight checks")

    backup_dir = os.path.join(usb, "logs", "backups", f"restore-main-{time.strftime('%Y%m%d%H%M%S')}")
    os.makedirs(backup_dir, exist_ok=True)

    os.makedirs(os.path.join(user_home, ".config", "Thunar"), exist_ok=True)
    os.makedirs(os.path.join(user_home, ".config", "com.ml4w.hyprlandsettings"), exist_ok=True)
    os.makedirs(os.path.join(user_home, ".local", "share", "icons"), exist_ok=True)

    hypr_conf = os.path.join(user_home, ".config", "hypr", "hyprland.conf")
    if os.path.isfile(hypr_conf):
        run(["sudo", "cp", "-a", hypr_conf, os.path.join(backup_dir, "hyprland.conf")], check=False)
        run(["sed", "-i", "s|^autogenerated = 1|# autogenerated = 1|", hypr_conf], check=False)

    sddm_conf = "/usr/lib/sddm/sddm.conf.d/default.conf"
    if os.path.isfile(sddm_conf):
        run(["sudo", "cp", "-a", sddm_conf, os.path.join(backup_dir, "sddm.default.conf")], check=False)
        run(["sudo", "sed", "-i", f"/^User=/s//User={user}/", sddm_conf], check=False)

    progress("Thunar")
    uca_src = os.path.join(usb, "dots", "uca.xml")
    uca_restored = "no"
    if os.path.isfile(uca_src):
        run(["rsync", "-arh", "--quiet", uca_src, os.path.join(user_home, ".config", "Thunar")])
        uca_restored = "yes"

    restored_dirs = []
    progress("User directories")
    for d in dirs:
        src = os.path.join(usb, "home", d)
        if os.path.exists(src):
            run(["rsync", "-arh", "--quiet", src, user_home])
            restored_dirs.append(d)

    cursor_restored = "no"
    progress("Icons and themes")
    cursor_src = os.path.join(usb, "home", "LyraX-cursors")
    if os.path.isdir(cursor_src):
        run(["rsync", "-arh", "--quiet", cursor_src, os.path.join(user_home, ".local", "share", "icons")])
        cursor_restored = "yes"

    icons_restored = "no"
    themes_restored = "no"
    if run(["rsync", "-arh", "--quiet", os.path.join(usb, "home", ".icons"), user_home], check=False).returncode == 0:
        icons_restored = "yes"
    if run(["rsync", "-arh", "--quiet", os.path.join(usb, "home", ".themes"), user_home], check=False).returncode == 0:
        themes_restored = "yes"

    dots_restored = "no"
    progress("Dotfiles")
    if run(["rsync", "-arh", "--quiet", os.path.join(usb, "dots"), user_home], check=False).returncode == 0:
        dots_restored = "yes"

    fonts_installed = "no"
    progress("Fonts")
    fonts_script = os.path.join(user_home, "Shared", "fonts", "install.sh")
    if os.path.isfile(fonts_script) and os.access(fonts_script, os.X_OK):
        if run(["bash", fonts_script], check=False).returncode == 0:
            fonts_installed = "yes"
    else:
        err(f"Font install script not found or not executable: {fonts_script}")

    yay_installed = "no"
    progress("Yay")
    if command_exists("pacman"):
        run(["sudo", "pacman", "-S", "--needed", "--noconfirm", "git", "base-devel"], check=False)
        yay_dir = os.path.join(user_home, "yay")
        if not os.path.isdir(yay_dir):
            run(["git", "clone", "https://aur.archlinux.org/yay.git", yay_dir], check=False)
        if run(["sudo", "-u", user, "bash", "-lc", f"cd {yay_dir} && makepkg -si --noconfirm"], check=False).returncode == 0:
            yay_installed = "yes"
    else:
        err("pacman not found; skipping yay install.")

    status("Restore done.")
    status(f"Target: {usb}")
    status(f"Log: {log_path}")
    if LOG_FH:
        LOG_FH.close()


if __name__ == "__main__":
    main()
